### ISSUE TITLE
Criar telas básicas do site

### ISSUE THREAD

**Issue by ro-anderson** [ro-anderson/frontend-PJI240#1]
## Referências

- card da task [task](https://www.notion.so/criar-telas-9574c2f1f62e46c7ab0202e62e528c2d) no notion.

- [panel](https://app.excalidraw.com/l/StdCnh2qXZ/7dZA75BGTDU) do excalidraw

## Tasks
Telas para implementar:
- [x]  Home - [http://localhost:5001/](http://localhost:5001/)
- [ ]  Cadastro - [http://localhost:5001/form1](http://localhost:5001/form1)
- [x]  Login - [http://localhost:5001/form2](http://localhost:5001/form2)
- [ ]  Sobre - [http://localhost:5001/page/about](http://localhost:5001/page/about)
- [ ]  Negociação - [http://localhost:5001/page/about](http://localhost:5001/page/about)
